### ISSUE TITLE
Błąd w trakcie dodawania podwyżki kierownikowi - brak error handlingu

### ISSUE THREAD

**Issue by annalyjak** [michalranowicz/homework5#1]
Error:
```
Exception in thread "main" java.lang.ClassCastException: class com.michalranowicz.homework5.SpecialPermissionsEmployee cannot be cast to class com.michalranowicz.homework5.BaseEmployee (com.michalranowicz.homework5.SpecialPermissionsEmployee and com.michalranowicz.homework5.BaseEmployee are in unnamed module of loader 'app')
	at com.michalranowicz.homework5.MainActivityKt.main(MainActivity.kt:203)
	at com.michalranowicz.homework5.MainActivityKt.main(MainActivity.kt)
```
Steps to reproduce:
1. Utwórz nowego pracownika typu kierownik
2. Dodaj podwyżkę pracownikowi, który jest kierownikiem (ten sam user dodaje sam sobie podwyżkę)

**Comment by annalyjak** [comment]
Ten sam problem występuje w sytuacji gdy inny kierownik daje podwyżkę innemu kierownikowi (nie musi dawać ją sam sobie)

```
Exception in thread "main" java.lang.ClassCastException: class com.michalranowicz.homework5.SpecialPermissionsEmployee cannot be cast to class com.michalranowicz.homework5.BaseEmployee (com.michalranowicz.homework5.SpecialPermissionsEmployee and com.michalranowicz.homework5.BaseEmployee are in unnamed module of loader 'app')
	at com.michalranowicz.homework5.MainActivityKt.main(MainActivity.kt:203)
	at com.michalranowicz.homework5.MainActivityKt.main(MainActivity.kt)
```

**Comment by michalranowicz** [comment]
tutaj zrobiłem try / catch (czy chodziło o takie rozwiązanie?)
try {
                            (manager as SpecialPermissionsEmployee).giveRaiseToEmployee(
                                employee as BaseEmployee,
                                raiseAmount
                            )
                        }catch (e: Exception){
                            println("Nie udało sie udzielić podwyżki. Posiadając uprawnienia kierownika można tylko udzielać podwyżki pracownikom niższego szczebla")
                        }

**Comment by annalyjak** [comment]
jasne, nie napisałam specjalnie jak masz to rozwiązać, bo nie wiedziałam na co się zdecydujesz (było kilka możliwości), ale ta jest jak najbardziej okej :D
